---
title: "REM vignette"
author: "Pablo Palencia"
date: "8 de abril de 2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# 1. Introduction

## 1.1 REM background
The Random Encounter Model (**REM**) is a method for estimating animal density from camera trap data without the need for individual recognition (Rowcliffe et al., 2008 - J. App. Ecol. 45: 1228-1236). Over the last years it has been used for a wide range of unmarked species (Cusack et al., 2015 - J. Wild. Manag. 79(6): 1014-1021; ENETWILD-consortium et al., 2019 - EFSA Supporting Publications - 16(9); Pfeffer et al., 2018 - Remote Sens. Ecol. Conserv. 2:84-94; Zero et al., 2013 - Oryx 47(3): 410-419).

## 1.2 Practical exercise
Here, I'm going to estimate population density of fallow deer (*Dama dama*) population samped with 30 camera traps. (Why fallow deer? Easy, is my favourite species, see Figure \@ref(fig:fallowdeer)).

#```{r fallowdeer, fig.align='center', fig.cap="One of the fallow deer of our target population", fig.width=2.5, fig.height=3.5, include=FALSE}

# Plot fallow deer  

#plot(region)
#```

Should be noted that all the necessary parameters to apply REM (i.e. day range, encounter rate and detection zone) will be derived from camera trap data. Without the need of auxiliary data. This required additional effort, especialy during image processing, but it is recommended taking into account the spatio-temporal variations in day range, and the variability in detection zone as function of target species, camera trap brand, settings and enviromental variables between others. Please, note that *remBoot* R package implemet REM calculations in R (Caravaggi, 2017 - J. Open Source Softw.- 2(10):176 ).

# 2. Importing dataframes and functions
Three dataframes are needed to run the analysis: i) the raw data of day range, detection zone and encounter rate, ii) the operativity matrix (information about camera traps functionality), and iii) camera trap coordinates (just for plots and exploratory analysis). 
Adittionally, we will need to import a couple of functions that are not included in an R package (these functions were devoloped by M. Rowcliffe and Distance Sampling folks from St. Andrews University).
